// export const CREATE_ITEM = 'CREATE_ITEM';
export const UPDATE_ITEM = 'UPDATE_ITEM';
export const DELETE_ITEM = 'DELETE_ITEM';
export const RESTORE_ITEM = 'RESTORE_ITEM';
export const UPDATE_ITEMS_TEXT = 'UPDATE_ITEMS_TEXT';
export const UPDATE_ITEMS_STATUS = 'UPDATE_ITEMS_STATUS';
export const CREATE_NEW_ITEM = 'CREATE_NEW_ITEM';